"""Дополнительные доменные понятия, которых ещё нет в курируемой онтологии
(data/seed_data.json), обнаруженные по реальным именам файлов/содержимому
в исходном корпусе (архив R&D по горному делу/металлургии: геомеханика,
закладочные работы, взрывные работы, переработка шлаков и т.д. наряду с уже
курируемыми сценариями гидро-/пирометаллургии меди/никеля).
"""

EXTRA_CONCEPTS = [
    {"id": "topic_geomechanics", "type": "Topic", "name_ru": "Геомеханика", "name_en": "Geomechanics",
     "aliases": ["геомеханическ", "geomechanics", "геомеханич"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_rockburst", "type": "Topic", "name_ru": "Удароопасность", "name_en": "Rockburst hazard",
     "aliases": ["удароопасн", "горный удар", "rockburst"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_backfill", "type": "Topic", "name_ru": "Закладочные работы", "name_en": "Mine backfill",
     "aliases": ["закладк", "закладочн", "backfill"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_blasting", "type": "Topic", "name_ru": "Взрывные работы", "name_en": "Blasting",
     "aliases": ["взрывн", "буровзрывн", "blasting"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_slag_flotation", "type": "Topic", "name_ru": "Флотация шлаков", "name_en": "Slag flotation",
     "aliases": ["флотаци", "flotation"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_chlorination", "type": "Topic", "name_ru": "Хлорное выщелачивание", "name_en": "Chlorination leaching",
     "aliases": ["хлорн", "хлорирован", "chlorination"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_cyanide_leaching", "type": "Topic", "name_ru": "Цианидное выщелачивание", "name_en": "Cyanide leaching",
     "aliases": ["цианидн", "cyanide"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_slag_depletion", "type": "Topic", "name_ru": "Обеднение шлаков", "name_en": "Slag depletion",
     "aliases": ["обеднен", "slag depletion"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_reinforcement", "type": "Topic", "name_ru": "Армировка горных выработок", "name_en": "Mine reinforcement",
     "aliases": ["армировк", "reinforcement"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_waterproofing", "type": "Topic", "name_ru": "Гидроизоляция", "name_en": "Waterproofing",
     "aliases": ["гидроизоляц", "waterproofing"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_bim", "type": "Topic", "name_ru": "Информационное моделирование (BIM)", "name_en": "Building information modeling",
     "aliases": ["bim", "информационное моделирование"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_automation", "type": "Topic", "name_ru": "Автоматизация горной отрасли", "name_en": "Mining automation",
     "aliases": ["автоматизаци", "automation"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_seismic", "type": "Topic", "name_ru": "Сейсмические нагрузки", "name_en": "Seismic loading",
     "aliases": ["сейсмическ", "seismic"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_ore_averaging", "type": "Topic", "name_ru": "Усреднение руды", "name_en": "Ore averaging/stockpiling",
     "aliases": ["усреднен", "складирован"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_tailings", "type": "Topic", "name_ru": "Хвосты обогащения", "name_en": "Tailings",
     "aliases": ["хвост", "tailings"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_lithium", "type": "Topic", "name_ru": "Литий", "name_en": "Lithium",
     "aliases": ["литий", "lithium"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_zinc_lead", "type": "Topic", "name_ru": "Цинк и свинец", "name_en": "Zinc and lead",
     "aliases": ["цинк", "свинец", "zinc", "lead"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_refractories", "type": "Topic", "name_ru": "Огнеупоры и футеровка печей", "name_en": "Refractories/furnace lining",
     "aliases": ["огнеупорн", "футеровк", "refractor"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_battery_recycling", "type": "Topic", "name_ru": "Переработка литий-ионных батарей", "name_en": "Li-ion battery recycling",
     "aliases": ["литий-ионн", "аккумулятор", "battery recycl"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_market_analysis", "type": "Topic", "name_ru": "Обзор рынка металлов", "name_en": "Metals market analysis",
     "aliases": ["рынок", "market"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_ore_grinding", "type": "Topic", "name_ru": "Дробление и измельчение руды", "name_en": "Crushing and grinding",
     "aliases": ["дроблен", "измельчен", "мельниц", "grinding"], "geography": "Global", "confidence": "verified"},
    {"id": "topic_synthetic_anhydrite", "type": "Topic", "name_ru": "Синтетический ангидрит (техногенный гипс)", "name_en": "Synthetic anhydrite",
     "aliases": ["ангидрит", "техногенный гипс", "anhydrite"], "geography": "Global", "confidence": "verified"},
]
